[tool.poetry]
name = "cosinorage"
version = "0.1.0"
description = ""
authors = ["Jacob Leo Oskar Hunecke"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
numpy = "^2.1.3"
pandas = "^2.2.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
